services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - WEBUI_PORT=8080
    volumes:
      - ./data/config:/config
      - ./data/downloads:/downloads
    restart: unless-stopped
    networks:
      - default
      - my_network

networks:
  my_network:
    external: true
