services:
  clipboard:
    build: .
    container_name: clipboard
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - default
      - my_network

networks:
  my_network:
    external: true
