services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - ../qbittorrent/data/downloads:/qb:ro
      - ../transcribe/data/downloads:/transcribed:ro
    ports:
      - "8096:8096"
    restart: unless-stopped
    networks:
      - default
      - my_network

networks:
  my_network:
    external: true
