services:
  flashcard-backend:
    build: ./backend
    container_name: flashcard-backend
    restart: unless-stopped
    volumes:
      - ./data:/data
    expose:
      - "8000"

  flashcard-frontend:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: flashcard-frontend
    restart: unless-stopped
    depends_on:
      - flashcard-backend
    networks:
      - default
      - my_network

networks:
  my_network:
    external: true
